### ISSUE TITLE
Simplify this repository

### ISSUE THREAD

**Issue by BILLthebuilder** [Opensource-254/Opensource-254.github.io#3]
**Is your feature request related to a problem? Please describe.**
- This repo has unnecessary complications

**Describe the solution you'd like**
- Let us make the repo with a single page to act as a placeholder until the org website is done

**Describe alternatives you've considered**
- A single page with markup and styling saying `Welcome to Opensource-254` or `Site coming soon`.

**Additional context**
- None

**Comment by stannlee** [comment]
Thank you billy the fix is in progress

**Comment by azim254** [comment]
yeah good idea badala ya complication mingi

**Comment by BILLthebuilder** [comment]
> Thank you billy the fix is in progress

Okay, good

**Comment by stannlee** [comment]
The repo is now clean
